from fastapi import APIRouter
from fastapi.responses import FileResponse

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER

from collections import defaultdict

from app.database import SessionLocal
from app.models.student import Student
from app.models.result import Result

router = APIRouter()


# =========================
# SUBJECTS
# =========================
ALL_SUBJECTS = [
    "Mathematics",
    "English",
    "Science",
    "Geography",
    "History",
    "Development Studies"
]


# =========================
# PDF STYLES
# =========================
styles = getSampleStyleSheet()

TitleStyle = ParagraphStyle(
    "TitleStyle",
    parent=styles["Title"],
    alignment=TA_CENTER,
    textColor=colors.darkblue,
    spaceAfter=10
)

CenterStyle = ParagraphStyle(
    "CenterStyle",
    parent=styles["BodyText"],
    alignment=TA_CENTER,
)

InfoStyle = ParagraphStyle(
    "InfoStyle",
    parent=styles["BodyText"],
    leading=18,
)

SummaryStyle = ParagraphStyle(
    "SummaryStyle",
    parent=styles["BodyText"],
    leading=20,
)

FooterStyle = ParagraphStyle(
    "FooterStyle",
    parent=styles["BodyText"],
    alignment=TA_CENTER,
    textColor=colors.grey
)

# =========================
# WATERMARK
# =========================
def add_watermark(canvas, doc):

    canvas.saveState()

    canvas.setFont("Helvetica-Oblique", 10)

    # Darker grey
    canvas.setFillColor(colors.darkgrey)

    # More visible transparency
    try:
        canvas.setFillAlpha(0.35)
    except:
        pass

    # Bottom center
    canvas.drawCentredString(
        300,
        25,
        "Generated by SchoolCore Academic Management System"
    )

    canvas.restoreState()

# =========================
# STUDENT REPORT
# =========================
@router.get("/report/student/{student_id}")
def generate_student_report(student_id: str):

    db = SessionLocal()

    try:

        # =========================
        # GET STUDENT
        # =========================
        student = db.query(Student).filter(
            Student.student_id == student_id
        ).first()

        if not student:
            return {"error": "Student not found"}

        # =========================
        # GET RESULTS
        # =========================
        results = db.query(Result).filter(
            Result.student_id == student_id
        ).all()

        grouped = defaultdict(list)

        for r in results:
            grouped[r.term].append(r)

        filename = f"{student_id}_report.pdf"

        doc = SimpleDocTemplate(
            filename,
            rightMargin=40,
            leftMargin=40,
            topMargin=40,
            bottomMargin=28
        )

        content = []

        # =========================
        # SCHOOL HEADER
        # =========================
        content.append(
            Paragraph("SCHOOLCORE ACADEMY", TitleStyle)
        )

        content.append(
            Paragraph(
                """
                Maseru, Lesotho<br/>
                Tel: +266 5352 2853<br/>
                Email: admin@schoolcore.com
                """,
                CenterStyle
            )
        )

        content.append(Spacer(1, 20))

        content.append(
            Paragraph("STUDENT REPORT CARD", TitleStyle)
        )

        content.append(Spacer(1, 20))

        # =========================
        # STUDENT INFO BOX
        # =========================
        info_data = [
            ["Student Name", f"{student.first_name} {student.last_name}"],
            ["Student ID", student.student_id],
            ["Class", student.class_name],
            ["Academic Year", "2026"],
        ]

        info_table = Table(info_data, colWidths=[160, 280])

        info_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.darkblue),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.whitesmoke),
            ("GRID", (0, 0), (-1, -1), 1, colors.black),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
            ("BACKGROUND", (1, 0), (1, -1), colors.beige),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ]))

        content.append(info_table)
        content.append(Spacer(1, 25))

        # =========================
        # CLASS STUDENTS
        # =========================
        class_students = db.query(Student).filter(
            Student.class_name == student.class_name
        ).all()

        class_ids = [s.student_id for s in class_students]

        overall_total = 0
        overall_count = 0

        terms = ["Term 1", "Term 2", "Term 3", "Term 4"]


        # =========================
        # TERM LOOP
        # =========================
        for index, term in enumerate(terms):

            if term not in grouped:
                continue

            # =========================
            # NEW PAGE PER TERM
            # =========================
            if index > 0:
                content.append(PageBreak())

            content.append(
                Paragraph(term, styles["Heading1"])
            )

            content.append(Spacer(1, 15))

            term_results = grouped[term]

            subject_map = {
                r.subject: r for r in term_results
            }

            table_data = [["Subject", "Score", "Grade"]]

            term_total = 0

            # =========================
            # SUBJECT TABLE
            # =========================
            for subject in ALL_SUBJECTS:

                if subject in subject_map:

                    r = subject_map[subject]

                    score = r.score
                    grade = r.grade

                    term_total += score
                    overall_total += score
                    overall_count += 1

                else:

                    score = 0
                    grade = "ABS"

                table_data.append([
                    subject,
                    str(score),
                    grade
                ])

            report_table = Table(
                table_data,
                colWidths=[240, 90, 90]
            )

            report_table.setStyle(TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),

                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("ROWBACKGROUNDS",
                 (0, 1),
                 (-1, -1),
                 [colors.whitesmoke, colors.beige]),

                ("ALIGN", (1, 1), (-1, -1), "CENTER"),

                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
            ]))

            content.append(report_table)

            content.append(Spacer(1, 20))

            # =========================
            # STUDENT AVERAGE
            # =========================
            student_total = sum(
                subject_map[s].score if s in subject_map else 0
                for s in ALL_SUBJECTS
            )

            student_avg = student_total / len(ALL_SUBJECTS)

            # =========================
            # CLASS AVERAGE
            # =========================
            class_results = db.query(Result).filter(
                Result.term == term,
                Result.student_id.in_(class_ids)
            ).all()

            class_avg = (
                sum(r.score for r in class_results) / len(class_results)
                if class_results else 0
            )

            # =========================
            # CLASS RANKING
            # =========================
            ranking = []

            for s in class_students:

                s_results = db.query(Result).filter(
                    Result.student_id == s.student_id,
                    Result.term == term
                ).all()

                s_map = {
                    r.subject: r for r in s_results
                }

                total = sum(
                    s_map[sub].score if sub in s_map else 0
                    for sub in ALL_SUBJECTS
                )

                avg = total / len(ALL_SUBJECTS)

                ranking.append({
                    "student_id": s.student_id,
                    "avg": avg
                })

            ranking.sort(
                key=lambda x: x["avg"],
                reverse=True
            )

            position = next(
                (
                    i + 1
                    for i, x in enumerate(ranking)
                    if x["student_id"] == student.student_id
                ),
                0
            )

            # =========================
            # REMARK LOGIC
            # =========================
            if student_avg >= 80:
                remark = "Excellent performance. Keep it up."
            elif student_avg >= 70:
                remark = "Very good performance."
            elif student_avg >= 50:
                remark = "Good effort. Continue working hard."
            else:
                remark = "Needs improvement."

            # =========================
            # SUMMARY BOX
            # =========================
            summary_data = [
                ["Student Average", f"{round(student_avg, 2)}"],
                ["Class Average", f"{round(class_avg, 2)}"],
                ["Position", f"{position} / {len(ranking)}"],
                ["Attendance", "Present"],
            ]

            summary_table = Table(
                summary_data,
                colWidths=[180, 180]
            )

            summary_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (0, -1), colors.lightblue),
                ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]))

            content.append(summary_table)

            content.append(Spacer(1, 8))

            # =========================
            # TOP 3 STUDENTS
            # =========================
            content.append(
                Paragraph(
                    "<b>Top 3 Students</b>",
                    styles["Heading3"]
                )
            )

            for pos, item in enumerate(ranking[:3], start=1):

                content.append(
                    Paragraph(
                        f"{pos}. {item['student_id']} - {round(item['avg'], 2)}%",
                        styles["BodyText"]
                    )
                )

            content.append(Spacer(1, 20))

            # =========================
            # REMARKS
            # =========================
            content.append(
                Paragraph(
                    f"<b>Teacher Remark:</b> {remark}",
                    SummaryStyle
                )
            )

            content.append(Spacer(1, 10))

            # =========================
            # SIGNATURES
            # =========================
            signatures = Table([
                [
                    "____________________\nClass Teacher",
                    "____________________\nPrincipal"
                ]
            ], colWidths=[220, 220])

            signatures.setStyle(TableStyle([
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ]))

            content.append(signatures)

            content.append(Spacer(1, 10))
 
           
        # =========================
        # FINAL SUMMARY
        # =========================
        if overall_count > 0:

            final_avg = overall_total / overall_count

            status = (
                "PROMOTED"
                if final_avg >= 50
                else "REPEAT"
            )

            content.append(
                Paragraph(
                    "FINAL ACADEMIC SUMMARY",
                    TitleStyle
                )
            )

            content.append(Spacer(1, 8))

            final_table = Table([
                ["Final Average", f"{round(final_avg, 2)}"],
                ["Promotion Status", status]
            ], colWidths=[220, 220])

            final_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (0, -1), colors.darkgreen),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.whitesmoke),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ]))

            content.append(final_table)

        # =========================
        # BUILD PDF
        # =========================
        doc.build(
            content,
            onFirstPage=add_watermark,
            onLaterPages=add_watermark
        )

        return FileResponse(
            filename,
            filename=filename,
            media_type="application/pdf"
        )

     
    except Exception as e:
        return {"error": str(e)}

    finally:
        db.close()
 
